version: "3"
networks:
  activity_net:
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "8888:8888"
      - "443:443"
    volumes:
      - /var/www/html/:/var/www/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reverseproxy/nginx_ssl.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html/.well-known:/usr/share/nginx/html/.well-known
      # - ./reverseproxy/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      # - ./reverseproxy/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
    networks:
      - activity_net
  activityfrontend:
    image: registry.digitalocean.com/imagerepo/activity:activityfrontend-8a7ed56
    volumes: 
      - ./reverseproxy/activity_frontend.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/:/var/www/html2
    networks:
      - activity_net

  activitydb:
    image: registry.digitalocean.com/imagerepo/activity:activitydb-fd10870
    ports:
      - "3306:3306"
    networks:
      - activity_net

  activitybackend:
    image: registry.digitalocean.com/imagerepo/activity:activitybackend-5ed0df8

   # ports:
    #   - "5000:5000"
    networks:
      - activity_net
