version: "3"
networks:
  host_net:
    external: true
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "8888:8888"
      - "443:443"
    volumes:
      - /var/www/html/:/var/www/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html/.well-known:/usr/share/nginx/html/.well-known
      # - ./reverseproxy/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      # - ./reverseproxy/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
    networks:
      - host_net
