---
- name: Install necessary pip modules
  shell: pip3 install docker docker-compose

- name: Tear down existing docker services
  community.docker.docker_compose:
    project_src: "{{working_dir}}"
    state: absent

- name: remove remove golang-docker-credential-helpers, to make doctl work
  apt:
    name: golang-docker-credential-helpers
    state: absent

- name: make sure, the digitalocean container registry can be accessed
  shell: doctl registry login --access-token {{token}}

- name: Install necessary pip modules
  shell: pip3 install docker docker-compose
