---
- name: Creates working_dir
  file:
    path: "{{ working_dir }}"
    state: directory

- name: Install necessary pip modules
  shell: pip3 install docker docker-compose

- name: remove golang-docker-credential-helpers, to make doctl work
  apt:
    name: golang-docker-credential-helpers
    state: absent

- name: Install necessary pip modules
  shell: pip3 install docker docker-compose

- name: Get running containers
  docker_host_info:
    containers: yes
  register: docker_info

- name: Stop running containers
  docker_container:
    name: "{{ item }}"
    state: stopped
  loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
