---
- name: Run with inline v2 compose
  hosts: all
  vars:
    working_dir: /home/compose
    provided_cers: false
    ansible_python_interpreter: "/usr/bin/python3"
    letsencrypt_account_key: /etc/letsencrypt/account/account.key
    domain_name: gruema.de
    sub_domain_names:
      - www
      - react
    acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
    # acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    acme_email: gruebler.martin@outlook.de
    acme_challenge_type: http-01
    letsencrypt_keys_dir: /etc/letsencrypt/keys
    letsencrypt_csrs_dir: /etc/letsencrypt/csrs
    letsencrypt_certs_dir: /etc/letsencrypt/certs
  roles:
    - name: system-preparation
      working_dir: /home/compose
    - name: ansible-doctl
      doctl_source_version: 1.59.0
    - name: https
    - name: run-compose
      working_dir: /home/compose
